function make_emosqp(target_dir, mex_cfile, embedded_mode)
% MAKE_EMOSQP Compile MEX interface for code-generated OSQP solver.
%
%   make_emosqp(target_dir, mex_cfile, embedded_mode)
%
%   target_dir    : directory containing the codegen output
%   mex_cfile     : path to emosqp_mex.c
%   embedded_mode : 1 (vectors only) or 2 (vectors + matrices)

% Mex command
mex_cmd = 'mex -O -silent';

% Compiler flags
mexoptflags = '-DMATLAB';
mexoptflags = sprintf('%s -DOSQP_EMBEDDED_MODE=%d', mexoptflags, embedded_mode);

% Linux: use c99
if ~ismac() && isunix()
    mexoptflags = sprintf('%s CFLAGS="$CFLAGS -std=c99"', mexoptflags);
end

% Optimizer flag
if ~ispc()
    mexoptflags = sprintf('%s COPTIMFLAGS=''-O3''', mexoptflags);
end

% Include directories (v1.0.0 codegen layout: inc/public, inc/private, root)
inc_flags = sprintf('-I%s', target_dir);
inc_public = fullfile(target_dir, 'inc', 'public');
inc_private = fullfile(target_dir, 'inc', 'private');
if exist(inc_public, 'dir')
    inc_flags = sprintf('%s -I%s -I%s', inc_flags, inc_public, inc_private);
else
    % Fallback: flat include layout
    inc_dir = fullfile(target_dir, 'include');
    if exist(inc_dir, 'dir')
        inc_flags = sprintf('%s -I%s', inc_flags, inc_dir);
    end
end

% Source files
cfiles = '';
src_dir = fullfile(target_dir, 'src');
if exist(src_dir, 'dir')
    src_files = dir(fullfile(src_dir, '*.c'));
    for i = 1:length(src_files)
        cfiles = sprintf('%s %s', cfiles, ...
            fullfile(src_dir, src_files(i).name));
    end
end

% Workspace source file (generated by osqp_codegen)
workspace_files = dir(fullfile(target_dir, '*workspace.c'));
for i = 1:length(workspace_files)
    cfiles = sprintf('%s %s', cfiles, ...
        fullfile(target_dir, workspace_files(i).name));
end

% Compile
fprintf('Compiling and linking emosqp MEX...');
cmd = sprintf('%s %s %s "%s" %s', mex_cmd, mexoptflags, inc_flags, mex_cfile, cfiles);
eval(cmd);
fprintf('\t\t[done]\n');

end
